name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - uses: actions/checkout@v4

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AND_NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_AND_NPM_TOKEN }}
        run: |
          yarn run release
